version: '3'
services:
  db:
    build:
      context: .
      dockerfile: Dockerfile-mysql
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysecretpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword

  app:
    stdin_open: true
    tty: true
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"

volumes:
  db_data: {}
