version: "3.8"
networks:
  app-tier:
    driver: bridge
services:
  # db:
  #   image: mysql:8.0
  #   container_name: intro_db
  #   restart: always
  #   env_file:
  #     - ./.env
  #   command: --default-authentication-plugin=mysql_native_password
  #     --bind-address=0.0.0.0
  #     --explicit_defaults_for_timestamp
  #   volumes:
  #     - ./sql:/docker-entrypoint-initdb.d
  #   ports:
  #     - 3306:3306
  #   networks:
  #     - app-tier

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - app-tier
